-- MySQL Script generated by MySQL Workbench
-- Tue Jun  7 09:16:39 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ezskins
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ezskins
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ezskins` DEFAULT CHARACTER SET utf8 ;
USE `ezskins` ;

-- -----------------------------------------------------
-- Table `ezskins`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ezskins`.`Usuarios` (
  `idusuario` INT NOT NULL auto_increment,
  `nome` VARCHAR(45) NOT NULL,
  `sobre_nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(60) NOT NULL,
  `trade_link` VARCHAR(255) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `rua_numero` VARCHAR(255) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(45) NOT NULL,
  `permissao` VARCHAR(45) NOT NULL
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ezskins`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ezskins`.`category` (
  `category_id` INT NOT NULL auto_increment,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `ezskins`.`Skins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ezskins`.`Skins` (
  `idskins` INT NOT NULL auto_increment,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(500) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(255) NOT NULL,
  `category_category_id` INT NOT NULL,
  PRIMARY KEY (`idskins`),
  INDEX `fk_Skins_category1_idx` (`category_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_Skins_category1`
    FOREIGN KEY (`category_category_id`)
    REFERENCES `ezskins`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ezskins`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ezskins`.`Compra` (
  `usuarios_idusuario` INT NOT NULL,
  `skins_idskins` INT NOT NULL,
  `data_compra` TIMESTAMP NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuarios_idusuario`, `skins_idskins`),
  INDEX `fk_Usuarios_has_Skins_Skins1_idx` (`skins_idskins` ASC) VISIBLE,
  INDEX `fk_Usuarios_has_Skins_Usuarios_idx` (`usuarios_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_has_Skins_Usuarios`
    FOREIGN KEY (`usuarios_idusuario`)
    REFERENCES `ezskins`.`Usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_has_Skins_Skins1`
    FOREIGN KEY (`skins_idskins`)
    REFERENCES `ezskins`.`Skins` (`idskins`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
